import { coinmarketcap } from './CoinMarketCap.js'

const cmc = new coinmarketcap()

//const test = await cmc.getCoinLogo("BTC,ETH,XRP")
//cmc.fetchCryptoData(5)

const data = {
    BTC: {
      id: 1,
      name: 'Bitcoin',
      symbol: 'BTC',
      category: 'coin',
      description: 'Bitcoin (BTC) is a cryptocurrency launched in 2010. Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,797,468. The last known price of Bitcoin is 106,251.34527661 USD and is down -0.16 over the last 24 hours. It is currently trading on 11844 active market(s) with $68,650,440,762.77 traded over the last 24 hours. More information can be found at https://bitcoin.org/.',
      slug: 'bitcoin',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1.png',
      subreddit: 'bitcoin',
      notice: '',
      tags: [
        'mineable',
        'pow',
        'sha-256',
        'store-of-value',
        'state-channel',
        'coinbase-ventures-portfolio',
        'three-arrows-capital-portfolio',
        'polychain-capital-portfolio',
        'binance-labs-portfolio',
        'blockchain-capital-portfolio',
        'boostvc-portfolio',
        'cms-holdings-portfolio',
        'dcg-portfolio',
        'dragonfly-capital-portfolio',
        'electric-capital-portfolio',
        'fabric-ventures-portfolio',
        'framework-ventures-portfolio',
        'galaxy-digital-portfolio',
        'huobi-capital-portfolio',
        'alameda-research-portfolio',
        'a16z-portfolio',
        '1confirmation-portfolio',
        'winklevoss-capital-portfolio',
        'usv-portfolio',
        'placeholder-ventures-portfolio',
        'pantera-capital-portfolio',
        'multicoin-capital-portfolio',
        'paradigm-portfolio',
        'bitcoin-ecosystem',
        'ftx-bankruptcy-estate',
        '2017-2018-alt-season'
      ],
      'tag-names': [
        'Mineable',
        'PoW',
        'SHA-256',
        'Store Of Value',
        'State Channel',
        'Coinbase Ventures Portfolio',
        'Three Arrows Capital Portfolio',
        'Polychain Capital Portfolio',
        'Binance Labs Portfolio',
        'Blockchain Capital Portfolio',
        'BoostVC Portfolio',
        'CMS Holdings Portfolio',
        'DCG Portfolio',
        'DragonFly Capital Portfolio',
        'Electric Capital Portfolio',
        'Fabric Ventures Portfolio',
        'Framework Ventures Portfolio',
        'Galaxy Digital Portfolio',
        'Huobi Capital Portfolio',
        'Alameda Research Portfolio',
        'a16z Portfolio',
        '1Confirmation Portfolio',
        'Winklevoss Capital Portfolio',
        'USV Portfolio',
        'Placeholder Ventures Portfolio',
        'Pantera Capital Portfolio',
        'Multicoin Capital Portfolio',
        'Paradigm Portfolio',
        'Bitcoin Ecosystem',
        'FTX Bankruptcy Estate ',
        '2017/18 Alt season'
      ],
      'tag-groups': [
        'OTHERS',   'ALGORITHM', 'ALGORITHM',
        'CATEGORY', 'CATEGORY',  'CATEGORY',
        'CATEGORY', 'CATEGORY',  'CATEGORY',
        'CATEGORY', 'CATEGORY',  'CATEGORY',
        'CATEGORY', 'CATEGORY',  'CATEGORY',
        'CATEGORY', 'CATEGORY',  'CATEGORY',
        'CATEGORY', 'CATEGORY',  'CATEGORY',
        'CATEGORY', 'CATEGORY',  'CATEGORY',
        'CATEGORY', 'CATEGORY',  'CATEGORY',
        'CATEGORY', 'PLATFORM',  'CATEGORY',
        'CATEGORY'
      ],
      urls: {
        website: [Array],
        twitter: [],
        message_board: [Array],
        chat: [],
        facebook: [],
        explorer: [Array],
        reddit: [Array],
        technical_doc: [Array],
        source_code: [Array],
        announcement: []
      },
      platform: null,
      date_added: '2010-07-13T00:00:00.000Z',
      twitter_username: '',
      is_hidden: 0,
      date_launched: '2010-07-13T00:00:00.000Z',
      contract_address: [],
      self_reported_circulating_supply: null,
      self_reported_tags: null,
      self_reported_market_cap: null,
      infinite_supply: false
    },
    ETH: {
      id: 1027,
      name: 'Ethereum',
      symbol: 'ETH',
      category: 'coin',
      description: 'Ethereum (ETH) is a cryptocurrency . Ethereum has a current supply of 120,451,108.89043379. The last known price of Ethereum is 3,928.73273903 USD and is down -3.37 over the last 24 hours. It is currently trading on 9692 active market(s) with $35,186,053,785.88 traded over the last 24 hours. More information can be found at https://www.ethereum.org/.',
      slug: 'ethereum',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
      subreddit: 'ethereum',
      notice: '',
      tags: [
        'pos',
        'smart-contracts',
        'ethereum-ecosystem',
        'coinbase-ventures-portfolio',
        'three-arrows-capital-portfolio',
        'polychain-capital-portfolio',
        'binance-labs-portfolio',
        'blockchain-capital-portfolio',
        'boostvc-portfolio',
        'cms-holdings-portfolio',
        'dcg-portfolio',
        'dragonfly-capital-portfolio',
        'electric-capital-portfolio',
        'fabric-ventures-portfolio',
        'framework-ventures-portfolio',
        'hashkey-capital-portfolio',
        'kenetic-capital-portfolio',
        'huobi-capital-portfolio',
        'alameda-research-portfolio',
        'a16z-portfolio',
        '1confirmation-portfolio',
        'winklevoss-capital-portfolio',
        'usv-portfolio',
        'placeholder-ventures-portfolio',
        'pantera-capital-portfolio',
        'multicoin-capital-portfolio',
        'paradigm-portfolio',
        'layer-1',
        'ftx-bankruptcy-estate'
      ],
      'tag-names': [
        'PoS',
        'Smart Contracts',
        'Ethereum Ecosystem',
        'Coinbase Ventures Portfolio',
        'Three Arrows Capital Portfolio',
        'Polychain Capital Portfolio',
        'Binance Labs Portfolio',
        'Blockchain Capital Portfolio',
        'BoostVC Portfolio',
        'CMS Holdings Portfolio',
        'DCG Portfolio',
        'DragonFly Capital Portfolio',
        'Electric Capital Portfolio',
        'Fabric Ventures Portfolio',
        'Framework Ventures Portfolio',
        'Hashkey Capital Portfolio',
        'Kenetic Capital Portfolio',
        'Huobi Capital Portfolio',
        'Alameda Research Portfolio',
        'a16z Portfolio',
        '1Confirmation Portfolio',
        'Winklevoss Capital Portfolio',
        'USV Portfolio',
        'Placeholder Ventures Portfolio',
        'Pantera Capital Portfolio',
        'Multicoin Capital Portfolio',
        'Paradigm Portfolio',
        'Layer 1',
        'FTX Bankruptcy Estate '
      ],
      'tag-groups': [
        'ALGORITHM', 'CATEGORY', 'PLATFORM',
        'CATEGORY',  'CATEGORY', 'CATEGORY',
        'CATEGORY',  'CATEGORY', 'CATEGORY',
        'CATEGORY',  'CATEGORY', 'CATEGORY',
        'CATEGORY',  'CATEGORY', 'CATEGORY',
        'CATEGORY',  'CATEGORY', 'CATEGORY',
        'CATEGORY',  'CATEGORY', 'CATEGORY',
        'CATEGORY',  'CATEGORY', 'CATEGORY',
        'CATEGORY',  'CATEGORY', 'CATEGORY',
        'CATEGORY',  'CATEGORY'
      ],
      urls: {
        website: [Array],
        twitter: [Array],
        message_board: [Array],
        chat: [Array],
        facebook: [],
        explorer: [Array],
        reddit: [Array],
        technical_doc: [Array],
        source_code: [Array],
        announcement: [Array]
      },
      platform: null,
      date_added: '2015-08-07T00:00:00.000Z',
      twitter_username: 'ethereum',
      is_hidden: 0,
      date_launched: null,
      contract_address: [
        [Object], [Object],
        [Object], [Object],
        [Object], [Object],
        [Object], [Object],
        [Object], [Object],
        [Object], [Object],
        [Object], [Object],
        [Object]
      ],
      self_reported_circulating_supply: null,
      self_reported_tags: null,
      self_reported_market_cap: null,
      infinite_supply: true
    },
    XRP: {
      id: 52,
      name: 'XRP',
      symbol: 'XRP',
      category: 'coin',
      description: 'XRP (XRP) is a cryptocurrency . XRP has a current supply of 99,986,858,106 with 57,187,870,382 in circulation. The last known price of XRP is 2.62037657 USD and is up 5.36 over the last 24 hours. It is currently trading on 1481 active market(s) with $16,560,681,813.39 traded over the last 24 hours. More information can be found at https://xrpl.org/.',
      slug: 'xrp',
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/52.png',
      subreddit: 'ripple',
      notice: '',
      tags: [
        'medium-of-exchange',
        'enterprise-solutions',
        'arrington-xrp-capital-portfolio',
        'galaxy-digital-portfolio',
        'a16z-portfolio',
        'pantera-capital-portfolio',
        'ftx-bankruptcy-estate',
        '2017-2018-alt-season'
      ],
      'tag-names': [
        'Medium of Exchange',
        'Enterprise Solutions',
        'Arrington XRP Capital Portfolio',
        'Galaxy Digital Portfolio',
        'a16z Portfolio',
        'Pantera Capital Portfolio',
        'FTX Bankruptcy Estate ',
        '2017/18 Alt season'
      ],
      'tag-groups': [
        'INDUSTRY',
        'INDUSTRY',
        'CATEGORY',
        'CATEGORY',
        'CATEGORY',
        'CATEGORY',
        'CATEGORY',
        'CATEGORY'
      ],
      urls: {
        website: [Array],
        twitter: [Array],
        message_board: [Array],
        chat: [],
        facebook: [],
        explorer: [Array],
        reddit: [Array],
        technical_doc: [Array],
        source_code: [Array],
        announcement: []
      },
      platform: {
        id: '1839',
        name: 'BNB',
        slug: 'bnb',
        symbol: 'BNB',
        token_address: '0x1d2f0da169ceb9fc7b3144628db156f3f6c60dbe'
      },
      date_added: '2013-08-04T00:00:00.000Z',
      twitter_username: 'Ripple',
      is_hidden: 0,
      date_launched: null,
      contract_address: [ [Object], [Object] ],
      self_reported_circulating_supply: null,
      self_reported_tags: null,
      self_reported_market_cap: null,
      infinite_supply: false
    }
}

const data2 = await cmc.fetchCoin("BTC")
//get the market cap data2.quote.USD.market_cap
//get the multiple would be marketcap of 2 / market cap of 1
//get new price of 1 would be current price of 1 * multiple
console.log(data2)