import { coinmarketcap } from './CoinMarketCap.js'

const cmc = new coinmarketcap()

const data = await cmc.fetchCryptoData(1000)
console.log(data)
const dic = [
    {
      id: 1,
      name: 'Bitcoin',
      symbol: 'BTC',
      slug: 'bitcoin',
      num_market_pairs: 11853,
      date_added: '2010-07-13T00:00:00.000Z',
      tags: [
        'mineable',
        'pow',
        'sha-256',
        'store-of-value',
        'state-channel',
        'coinbase-ventures-portfolio',
        'three-arrows-capital-portfolio',
        'polychain-capital-portfolio',
        'binance-labs-portfolio',
        'blockchain-capital-portfolio',
        'boostvc-portfolio',
        'cms-holdings-portfolio',
        'dcg-portfolio',
        'dragonfly-capital-portfolio',
        'electric-capital-portfolio',
        'fabric-ventures-portfolio',
        'framework-ventures-portfolio',
        'galaxy-digital-portfolio',
        'huobi-capital-portfolio',
        'alameda-research-portfolio',
        'a16z-portfolio',
        '1confirmation-portfolio',
        'winklevoss-capital-portfolio',
        'usv-portfolio',
        'placeholder-ventures-portfolio',
        'pantera-capital-portfolio',
        'multicoin-capital-portfolio',
        'paradigm-portfolio',
        'bitcoin-ecosystem',
        'ftx-bankruptcy-estate',
        '2017-2018-alt-season'
      ],
      max_supply: 21000000,
      circulating_supply: 19803640,
      total_supply: 19803640,
      infinite_supply: false,
      platform: null,
      cmc_rank: 1,
      self_reported_circulating_supply: null,
      self_reported_market_cap: null,
      tvl_ratio: null,
      last_updated: '2024-12-31T06:46:00.000Z',
      quote: { USD: [Object] }
    },
    {
      id: 1027,
      name: 'Ethereum',
      symbol: 'ETH',
      slug: 'ethereum',
      num_market_pairs: 9762,
      date_added: '2015-08-07T00:00:00.000Z',
      tags: [
        'pos',
        'smart-contracts',
        'ethereum-ecosystem',
        'coinbase-ventures-portfolio',
        'three-arrows-capital-portfolio',
        'polychain-capital-portfolio',
        'binance-labs-portfolio',
        'blockchain-capital-portfolio',
        'boostvc-portfolio',
        'cms-holdings-portfolio',
        'dcg-portfolio',
        'dragonfly-capital-portfolio',
        'electric-capital-portfolio',
        'fabric-ventures-portfolio',
        'framework-ventures-portfolio',
        'hashkey-capital-portfolio',
        'kenetic-capital-portfolio',
        'huobi-capital-portfolio',
        'alameda-research-portfolio',
        'a16z-portfolio',
        '1confirmation-portfolio',
        'winklevoss-capital-portfolio',
        'usv-portfolio',
        'placeholder-ventures-portfolio',
        'pantera-capital-portfolio',
        'multicoin-capital-portfolio',
        'paradigm-portfolio',
        'layer-1',
        'ftx-bankruptcy-estate'
      ],
      max_supply: null,
      circulating_supply: 120472682.07030922,
      total_supply: 120472682.07030922,
      infinite_supply: true,
      platform: null,
      cmc_rank: 2,
      self_reported_circulating_supply: null,
      self_reported_market_cap: null,
      tvl_ratio: null,
      last_updated: '2024-12-31T06:46:00.000Z',
      quote: { USD: [Object] }
    }
  ]